sudo: required
env:
  global:
    - PGPORT=5433
    - PGHOST=localhost
    - DATABASE_URL=postgres://localhost:5433/test-bookmarks
language: node_js
node_js: node
services:
  - postgresql
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'CREATE DATABASE test-bookmarks;'
